# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "Python-Box"
  end

  #config.vm.provision "file", source: "ssh/config", destination: ".ssh/config" 
  #config.vm.provision "file", source: "ssh/id_rsa", destination: ".ssh/id_rsa" 
  #config.vm.provision "file", source: "ssh/id_rsa.pub", destination: ".ssh/id_rsa.pub" 
  #config.vm.provision "file", source: "etc/aws-vars", destination: "/tmp/aws-vars" 

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y python3-pip
  SHELL
end
